### ISSUE TITLE
_map function is not applied to _cache when calling subscriber.emit in combine_latest.py

### ISSUE THREAD

**Issue by flofeurstein** [semiversus/python-broqer#1]
In combine_latest.py subscriber.emit is called directly with self._cache even if there is a _map function

https://github.com/semiversus/python-broqer/blob/551d11dfdc4a24c5e652f7582dac69a23a1f6366/broqer/op/combine_latest.py#L50

**Comment by semiversus** [comment]
Had the same issue and forgot to push it. Thx!
