### ISSUE TITLE
'hello world' showcase doesn't work.

### ISSUE THREAD

**Issue by badiku** [semiversus/python-broqer#29]
```
>>> i = Value('Attribute access made REACTIVE')
>>> i.lower().strip(sep=' ') | op.Sink(print)
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "site-packages\broqer\op\operator_overloading.py", line 148, in _getattr
    raise AttributeError('Attribute %r not found' % attribute_name)
**AttributeError: Attribute 'lower' not found**

this works:
`i | op.Map(str.lower) | op.Map(str.split) | op.Sink(print)`

py3.7

**Comment by semiversus** [comment]
Thanks badiku! Operator overloading has to be enabled. In the past it was automatic, but this was problematic as any attribute and method is allowed by definition and you can only detect the problem when the code is executed, e.g. typos like `i.emti` instead `i.emit` passed silently.

I fixed the example and detected another problem I fixed additionally. Commit 1d7169856908bc39f6e8a9b7778aee18646c0b17 is fixing it.
