### ISSUE TITLE
SinkAsync does not use the error_callback

### ISSUE THREAD

**Issue by phettberg** [semiversus/python-broqer#45]
In `SinkAsync`, `error_callback` is set as attribute in init, however it is never used. 
```python
def __init__(self, coro, *args, mode=AsyncMode.CONCURRENT,
             error_callback=default_error_handler,
             unpack: bool = False, **kwargs) -> None:

    _coro = wrap_coro(coro, unpack, *args, **kwargs)
    self._coro_queue = CoroQueue(_coro, mode=mode)
    self._error_callback = error_callback

def emit(self, value: Any, who: Publisher):
    self._coro_queue.schedule(value)
```
In the `emit` method, the `future` reference of `CoroQueue.schedule` should be used to add all callback which checks for an Exception and then finally calls `self._error_callback`.

**Comment by semiversus** [comment]
Yes, your're right. Will fix it on the weekend. Otherwise you could provide a pull request and I'll merge it.
